import 'package:expense_track/models/category_item.dart';
import 'package:flutter/material.dart';

final List<CategoryItem> predefinedCategories = [
  // Income Categories
  CategoryItem(
    id: 'salary',
    name: 'Salary',
    type: 'Income',
    iconCodePoint: Icons.attach_money.codePoint,
    fontFamily: Icons.attach_money.fontFamily,
    fontPackage: Icons.attach_money.fontPackage,
  ),
  CategoryItem(
    id: 'gift',
    name: 'Gift',
    type: 'Income',
    iconCodePoint: Icons.card_giftcard.codePoint,
    fontFamily: Icons.card_giftcard.fontFamily,
    fontPackage: Icons.card_giftcard.fontPackage,
  ),
  CategoryItem(
    id: 'award',
    name: 'Award',
    type: 'Income',
    iconCodePoint: Icons.emoji_events.codePoint,
    fontFamily: Icons.emoji_events.fontFamily,
    fontPackage: Icons.emoji_events.fontPackage,
  ),
  CategoryItem(
    id: 'investment',
    name: 'Investment',
    type: 'Income',
    iconCodePoint: Icons.trending_up.codePoint,
    fontFamily: Icons.trending_up.fontFamily,
    fontPackage: Icons.trending_up.fontPackage,
  ),
  CategoryItem(
    id: 'freelance',
    name: 'Freelance',
    type: 'Income',
    iconCodePoint: Icons.work.codePoint,
    fontFamily: Icons.work.fontFamily,
    fontPackage: Icons.work.fontPackage,
  ),
  CategoryItem(
    id: 'rental',
    name: 'Rental Income',
    type: 'Income',
    iconCodePoint: Icons.home_work.codePoint,
    fontFamily: Icons.home_work.fontFamily,
    fontPackage: Icons.home_work.fontPackage,
  ),
  CategoryItem(
    id: 'business',
    name: 'Business',
    type: 'Income',
    iconCodePoint: Icons.business_center.codePoint,
    fontFamily: Icons.business_center.fontFamily,
    fontPackage: Icons.business_center.fontPackage,
  ),

  // Expense Categories
  CategoryItem(
    id: 'food',
    name: 'Food',
    type: 'Expense',
    iconCodePoint: Icons.fastfood.codePoint,
    fontFamily: Icons.fastfood.fontFamily,
    fontPackage: Icons.fastfood.fontPackage,
  ),
  CategoryItem(
    id: 'house',
    name: 'House',
    type: 'Expense',
    iconCodePoint: Icons.house.codePoint,
    fontFamily: Icons.house.fontFamily,
    fontPackage: Icons.house.fontPackage,
  ),
  CategoryItem(
    id: 'clothing',
    name: 'Clothing',
    type: 'Expense',
    iconCodePoint: Icons.checkroom.codePoint,
    fontFamily: Icons.checkroom.fontFamily,
    fontPackage: Icons.checkroom.fontPackage,
  ),
  CategoryItem(
    id: 'transport',
    name: 'Transport',
    type: 'Expense',
    iconCodePoint: Icons.directions_car.codePoint,
    fontFamily: Icons.directions_car.fontFamily,
    fontPackage: Icons.directions_car.fontPackage,
  ),
  CategoryItem(
    id: 'shopping',
    name: 'Shopping',
    type: 'Expense',
    iconCodePoint: Icons.shopping_bag.codePoint,
    fontFamily: Icons.shopping_bag.fontFamily,
    fontPackage: Icons.shopping_bag.fontPackage,
  ),
  CategoryItem(
    id: 'medical',
    name: 'Medical',
    type: 'Expense',
    iconCodePoint: Icons.medical_services.codePoint,
    fontFamily: Icons.medical_services.fontFamily,
    fontPackage: Icons.medical_services.fontPackage,
  ),
  CategoryItem(
    id: 'present',
    name: 'Gift',
    type: 'Expense',
    iconCodePoint: Icons.card_giftcard.codePoint,
    fontFamily: Icons.card_giftcard.fontFamily,
    fontPackage: Icons.card_giftcard.fontPackage,
  ),
  CategoryItem(
    id: 'entertainment',
    name: 'Entertainment',
    type: 'Expense',
    iconCodePoint: Icons.movie.codePoint,
    fontFamily: Icons.movie.fontFamily,
    fontPackage: Icons.movie.fontPackage,
  ),
  CategoryItem(
    id: 'bills',
    name: 'Bills',
    type: 'Expense',
    iconCodePoint: Icons.receipt.codePoint,
    fontFamily: Icons.receipt.fontFamily,
    fontPackage: Icons.receipt.fontPackage,
  ),
  CategoryItem(
    id: 'education',
    name: 'Education',
    type: 'Expense',
    iconCodePoint: Icons.school.codePoint,
    fontFamily: Icons.school.fontFamily,
    fontPackage: Icons.school.fontPackage,
  ),
  CategoryItem(
    id: 'travel',
    name: 'Travel',
    type: 'Expense',
    iconCodePoint: Icons.flight_takeoff.codePoint,
    fontFamily: Icons.flight_takeoff.fontFamily,
    fontPackage: Icons.flight_takeoff.fontPackage,
  ),
  CategoryItem(
    id: 'subscription',
    name: 'Subscription',
    type: 'Expense',
    iconCodePoint: Icons.subscriptions.codePoint,
    fontFamily: Icons.subscriptions.fontFamily,
    fontPackage: Icons.subscriptions.fontPackage,
  ),
];
